# Loading the Dataset

In [1]:
import pandas as pd
import numpy as np
import csv
filename='E:/fizics honurs not sho eazi/###INTERNSHIP(SPACE WEATHER)/#New folder/sw_classification_data.txt'
table=np.loadtxt(filename,skiprows=6)
table.shape

(8625, 18)

In [2]:
df=pd.DataFrame(table,columns=['yr','mon','day','hr','flag','Bt','Np','Tp(K)','Vp','Sp','Va','Tex/Tp','Na/Np','Pd','Ey','bta','Ma','Mf'])
df.head()

yr  mon  day    hr  flag      Bt      Np   Tp(K)      Vp      Sp  \
0  1995.0  2.0  8.0   7.0   4.0  0.9250 -0.3638 -0.7703 -0.3763 -0.6618   
1  1995.0  2.0  8.0   8.0   4.0  0.9468 -0.2611 -0.7691 -0.3544 -0.6785   
2  1995.0  2.0  8.0   9.0   4.0  1.0121 -0.2098 -0.8870 -0.4127 -0.7494   
3  1995.0  2.0  8.0  10.0   4.0  1.0339  0.0126 -0.9311 -0.4565 -0.7869   
4  1995.0  2.0  8.0  11.0   4.0  1.1427 -0.1414 -0.9405 -0.4929 -0.7849   

       Va  Tex/Tp   Na/Np      Pd      Ey     bta      Ma     Mf  
0  0.8250  0.1800 -0.3294 -0.4889  1.8953 -0.4069 -0.9616 -1.394  
1  0.7122  0.1968 -0.8299 -0.4054  1.7812 -0.4014 -0.9106 -1.254  
2  0.7122  0.6320 -1.0995 -0.4165  1.4432 -0.4051 -0.9276 -1.324  
3  0.5054  0.8998 -1.1380 -0.2218  1.0292 -0.3959 -0.8597 -1.114  
4  0.7310  0.9277 -1.2150 -0.4110  0.8602 -0.4069 -0.9616 -1.394

In [3]:
df_target=pd.DataFrame(table[:,4],columns=['Solar Wind Flag'])
df_target.head()

Solar Wind Flag
0              4.0
1              4.0
2              4.0
3              4.0
4              4.0

In [4]:
df_info=pd.DataFrame(table[:,5:18],columns=['Bt','Np','Tp(K)','Vp','Sp','Va','Tex/Tp','Na/Np','Pd','Ey','bta','Ma','Mf'])
df_info.head()

Bt      Np   Tp(K)      Vp      Sp      Va  Tex/Tp   Na/Np      Pd  \
0  0.9250 -0.3638 -0.7703 -0.3763 -0.6618  0.8250  0.1800 -0.3294 -0.4889   
1  0.9468 -0.2611 -0.7691 -0.3544 -0.6785  0.7122  0.1968 -0.8299 -0.4054   
2  1.0121 -0.2098 -0.8870 -0.4127 -0.7494  0.7122  0.6320 -1.0995 -0.4165   
3  1.0339  0.0126 -0.9311 -0.4565 -0.7869  0.5054  0.8998 -1.1380 -0.2218   
4  1.1427 -0.1414 -0.9405 -0.4929 -0.7849  0.7310  0.9277 -1.2150 -0.4110   

       Ey     bta      Ma     Mf  
0  1.8953 -0.4069 -0.9616 -1.394  
1  1.7812 -0.4014 -0.9106 -1.254  
2  1.4432 -0.4051 -0.9276 -1.324  
3  1.0292 -0.3959 -0.8597 -1.114  
4  0.8602 -0.4069 -0.9616 -1.394

In [5]:
print(df.groupby('flag').size())

flag
1.0    2881
2.0    2215
3.0    1694
4.0    1835
dtype: int64


# Train Test Split

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df_info,np.ravel(df_target),test_size=0.20,random_state=101)

In [7]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(6900, 13) (1725, 13) (6900,) (1725,)


In [8]:
print(X_train.head(10))

          Bt      Np   Tp(K)      Vp      Sp      Va  Tex/Tp   Na/Np      Pd  \
5813 -1.0345  1.2272 -0.9919 -1.2951 -0.8391 -1.0926  0.1410 -1.2535 -0.1494   
1234 -0.0112 -0.4322 -0.9002  0.7540 -0.7348  0.0730  3.2991  3.6368  0.6741   
2305 -0.5337 -0.6204  0.7126  1.0967  0.5955 -0.2654 -0.1938  0.0942 -0.0381   
2986 -0.3596 -0.8770  1.8274  2.1468  2.8058  0.4490 -0.0878 -0.9070 -0.4277   
4128 -0.8603 -0.7915  0.5305  1.1478  0.8416 -0.4346 -0.1045  0.4408 -0.4221   
3453 -0.7079 -0.7573  1.2604  1.6582  1.4567 -0.2842 -0.1324  0.4023 -0.0882   
8175 -0.7515 -0.2440 -0.7104 -0.7482 -0.6472 -0.6978 -0.2384 -0.9070 -0.6280   
1531  0.3154  1.0733 -0.8856 -0.9159 -0.8036 -0.3782  0.0182  0.5563  0.4849   
6436 -0.4031 -0.1756 -0.2257 -0.4492 -0.3991 -0.4534 -0.4505  0.2867 -0.2663   
1818  0.4025 -0.5520 -0.9958 -0.6607 -0.7869  0.6182  1.3295 -0.6759 -0.8394   

          Ey     bta      Ma     Mf  
5813 -0.1073  1.9258  2.2140  0.566  
1234 -1.3916 -0.3574 -0.2314  0.916  
2305 

# Train the KNN Classifier

In [9]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [10]:
predictions=model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Result of first 20 predictions')
for x in range (0,20):
    print('>Actual:',predictions[x],'>Predicted:',y_test[x])

print('.\nAccuracy:'+repr(100*(accuracy_score(y_test,predictions))) +'%')
print('\nConfusion Matrix:\n',confusion_matrix(y_test,predictions))
print('\nClassification Report:\n',classification_report(y_test,predictions))


Result of first 20 predictions
>Actual: 3.0 >Predicted: 3.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 3.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 3.0 >Predicted: 3.0
.
Accuracy:91.18840579710145%

Confusion Matrix:
 [[552   2   0   2]
 [  2 382  31  13]
 [  6  47 296  16]
 [  3  19  11 343]]

Classification Report:
               precision    recall  f1-score   support

         1.0       0.98      0.99      0.99       556
         2.0       0.85      0.89      0.87       428
         3.0       0.88      0.81      0.84       365
         4.0       0

# Train the Linear Support Vector Machine Classifier

In [11]:
from sklearn.svm import SVC
model=SVC(kernel='linear')
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [12]:
predictions=model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Result of first 20 predictions')
for x in range (0,20):
    print('>Actual:',predictions[x],'>Predicted:',y_test[x])

print('.\nAccuracy:'+repr(100*(accuracy_score(y_test,predictions))) +'%')
print('\nConfusion Matrix:\n',confusion_matrix(y_test,predictions))
print('\nClassification Report:\n',classification_report(y_test,predictions))


Result of first 20 predictions
>Actual: 3.0 >Predicted: 3.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 3.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 3.0 >Predicted: 3.0
.
Accuracy:86.55072463768117%

Confusion Matrix:
 [[554   1   1   0]
 [  1 361  44  22]
 [ 12  84 242  27]
 [  4  27   9 336]]

Classification Report:
               precision    recall  f1-score   support

         1.0       0.97      1.00      0.98       556
         2.0       0.76      0.84      0.80       428
         3.0       0.82      0.66      0.73       365
         4.0       0

# Train the RBF Support Vector Machine Classifier

In [13]:
from sklearn.svm import SVC
model=SVC(kernel='rbf')
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
predictions=model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Result of first 20 predictions')
for x in range (0,20):
    print('>Actual:',predictions[x],'>Predicted:',y_test[x])

print('.\nAccuracy:'+repr(100*(accuracy_score(y_test,predictions))) +'%')
print('\nConfusion Matrix:\n',confusion_matrix(y_test,predictions))
print('\nClassification Report:\n',classification_report(y_test,predictions))


Result of first 20 predictions
>Actual: 3.0 >Predicted: 3.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 3.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 3.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 3.0 >Predicted: 3.0
.
Accuracy:88.05797101449275%

Confusion Matrix:
 [[552   2   2   0]
 [  1 365  49  13]
 [  7  74 259  25]
 [  3  21   9 343]]

Classification Report:
               precision    recall  f1-score   support

         1.0       0.98      0.99      0.99       556
         2.0       0.79      0.85      0.82       428
         3.0       0.81      0.71      0.76       365
         4.0       0

# Train the Naive Bayes Classifier

In [15]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [16]:
predictions=model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Result of first 20 predictions')
for x in range (0,20):
    print('>Actual:',predictions[x],'>Predicted:',y_test[x])

print('.\nAccuracy:'+repr(100*(accuracy_score(y_test,predictions))) +'%')
print('\nConfusion Matrix:\n',confusion_matrix(y_test,predictions))
print('\nClassification Report:\n',classification_report(y_test,predictions))


Result of first 20 predictions
>Actual: 3.0 >Predicted: 3.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 3.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 3.0 >Predicted: 3.0
.
Accuracy:83.30434782608695%

Confusion Matrix:
 [[545   4   1   6]
 [  6 348  50  24]
 [  7  96 243  19]
 [  3  51  21 301]]

Classification Report:
               precision    recall  f1-score   support

         1.0       0.97      0.98      0.98       556
         2.0       0.70      0.81      0.75       428
         3.0       0.77      0.67      0.71       365
         4.0       0

# Train the Decision Tree Classifier

In [17]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
predictions=model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Result of first 20 predictions')
for x in range (0,20):
    print('>Actual:',predictions[x],'>Predicted:',y_test[x])

print('.\nAccuracy:'+repr(100*(accuracy_score(y_test,predictions))) +'%')
print('\nConfusion Matrix:\n',confusion_matrix(y_test,predictions))
print('\nClassification Report:\n',classification_report(y_test,predictions))


Result of first 20 predictions
>Actual: 4.0 >Predicted: 3.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 3.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 3.0 >Predicted: 3.0
.
Accuracy:88.81159420289855%

Confusion Matrix:
 [[544   2   5   5]
 [  5 362  49  12]
 [  3  50 286  26]
 [  3  20  13 340]]

Classification Report:
               precision    recall  f1-score   support

         1.0       0.98      0.98      0.98       556
         2.0       0.83      0.85      0.84       428
         3.0       0.81      0.78      0.80       365
         4.0       0

# Train the Logistic Regression Classifier

In [19]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
predictions=model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Result of first 20 predictions')
for x in range (0,20):
    print('>Actual:',predictions[x],'>Predicted:',y_test[x])

print('.\nAccuracy:'+repr(100*(accuracy_score(y_test,predictions))) +'%')
print('\nConfusion Matrix:\n',confusion_matrix(y_test,predictions))
print('\nClassification Report:\n',classification_report(y_test,predictions))


Result of first 20 predictions
>Actual: 3.0 >Predicted: 3.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 3.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 4.0 >Predicted: 4.0
>Actual: 1.0 >Predicted: 1.0
>Actual: 2.0 >Predicted: 2.0
>Actual: 3.0 >Predicted: 3.0
.
Accuracy:86.02898550724638%

Confusion Matrix:
 [[548   7   1   0]
 [  1 362  44  21]
 [  8  95 239  23]
 [  3  26  12 335]]

Classification Report:
               precision    recall  f1-score   support

         1.0       0.98      0.99      0.98       556
         2.0       0.74      0.85      0.79       428
         3.0       0.81      0.65      0.72       365
         4.0       0